### PR TITLE
add support for steam deck audio

### PR DESCRIPTION
**Pull request by alkazar**
Will also need to add the following to the PKGBUILD:

```
	# Install alsa tweaks
	mkdir -p "${pkgdir}/usr/share"
	cp -R "usr/share/alsa" "${pkgdir}/usr/share/"
```

### CODE REVIEW

**Comment by alkazar** [comment]
We need to make this only apply to the Steam Deck. There are reportedly other devices with the same audio chipset for which this will break audio.

**Comment by pastaq** [comment]
Will this work if placed in etc instead of usr? Putting it on the immutable section posses more difficulty in being selective in implementation.

**Comment by Samsagax** [comment]
Wouldn´t it be better to build ALSA conf files package from git? I think the ucm2 files are already there for the Deck, but not yet released: https://github.com/alsa-project/alsa-ucm-conf/commit/6dd80aee34dbff85de5818b9181bb382dfe868ec

**Comment by alkazar** [comment]
This was resolved by @Samsagax by using `alsa-ucm-conf-git`

**Pull request closed without merging**
