### PR TITLE
Add systemd unit and script to fix AYANEO AIR Phased Audio

### PR DESCRIPTION
**Pull request by pastaq**

### CODE REVIEW

**Comment by pastaq** [comment]
requires adding [swh-plugins](https://archlinux.org/packages/?name=swh-plugins) as a dependency

**Comment by Samsagax** [comment]
After this is merged, PKGBUILD needs update.
install [/usr/lib/systemd/user/aya-air-audio.service](https://github.com/ChimeraOS/device-quirks/blob/air-audio/usr/lib/systemd/user/aya-air-audio.service)
install [/usr/bin/device-quirks/aya-neo-air-audio-phase-fix](https://github.com/ChimeraOS/device-quirks/blob/air-audio/usr/bin/device-quirks/aya-neo-air-audio-phase-fix)
add [swh-plugins](https://archlinux.org/packages/?name=swh-plugins) as a dependency

**Comment by Samsagax** [comment]
Should make a Wiki or a Readme entry to clarify some of these quirks. I'm perfectly fine with this as an optional dependency so the package can be installed and the service inactive.
Otherwise it LGTM

**Comment by pastaq** [comment]
Wiki makes sense, and we can link to it in the official wiki.

**Comment by Samsagax** [comment]
I guess the PKGBUILD needs to be updated again with this one right?

**Comment by pastaq** [comment]
Yes. I'm working on the wiki format but it's a drag.

**Comment by Samsagax** [comment]
PKGBUILD updated

**Pull request merged**
